tools:
  domain:
    amass:
      toolname: amass
    ksubdomain:
      toolname: ksubdomain
    subfinder:
      toolname: subfinder
    oneforall:
      toolname: oneforall
    ip2location:
      toolname: ip2location
    subnames_big:
      # https://raw.githubusercontent.com/shmilylty/OneForAll/blob/master/data/subnames_big.7z
      toolname: subnames_big
    ip2region:
      toolname: ip2region
  emailcollect:
    emailall:
      toolname: emailall
  survivaldetect:
    httpx:
      toolname: httpx
  finger:
    ehole:
      toolname: ehole
    webanalyze:
      toolname: webanalyze
  portscan:
    TxPortMap:
      toolname: TxPortMap
    # 暂不使用
    dismap:
      toolname: dismap
    naabu:
      toolname: naabu
  sensitiveinfo:
    # 如果runtime为空则不限时，如果为0 则跳过该工具执行，如果为指定数字则限时执行
    chrome:
      toolname: chrome
    crawlergo:
      toolname: crawlergo
      runtime:
    rad:
      toolname: rad
      runtime: 900
    gospider:
      toolname: gospider
      runtime: 600
    hakrawler:
      # 修改了加了-f参数
      toolname: hakrawler
      runtime: 600
    dirsearch:
      # zanbuyong，不移动 dirsearch-master/ /
      toolname: dirsearch
    gau:
      toolname: gau
      runtime: 600
    urlcollector:
      toolname: urlcollector
      runtime: 600
    URLFinder:
      toolname: URLFinder
      runtime: 600
  vulscan:
    afrog:
      toolname: afrog
    goon:
      toolname: goon
    nuclei:
      toolname: nuclei
    SweetBabyScan:
      toolname: SweetBabyScan
    vulmap:
      # py
      toolname: vulmap
    vscan:
      toolname: vscan
  other:
    xray:
      toolname: xray
      listenport: 7777


































